import { useMemo } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, CalendarDays, Clock3, FileText, MapPin, Package, Wallet } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { serviceStageLabels, type ServiceStage } from '../../src/business-contract.ts';
import type { PageProps } from './api';
import { dateTime, EmptyState, localDateTime, money, quantity } from './ui';

const serviceStages = Object.keys(serviceStageLabels) as ServiceStage[];
const compactMoney = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', notation: 'compact', maximumFractionDigits: 1 });
const dateLabel = (value: string) => value.split('-').reverse().join('/');

export function OverviewPage({ data, month }: PageProps) {
  const { summary } = data;
  const clientNames = useMemo(() => new Map(data.clients.map((client) => [client.id, client.name])), [data.clients]);
  const upcoming = data.visits.filter((visit) => visit.status === 'scheduled' && visit.endAt > new Date().toISOString()).sort((a, b) => a.startAt.localeCompare(b.startAt)).slice(0, 4);
  const lowStock = data.materials.filter((material) => material.active && material.stockMilli <= material.minimumMilli).sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
  const stageCounts = new Map(summary.serviceStages.map((item) => [item.stage, item.count]));
  const totalServices = summary.serviceStages.reduce((total, item) => total + item.count, 0);
  const monthLabel = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${month}-01T12:00:00Z`));
  const hasCash = summary.cash.openingCents !== 0 || summary.cash.incomeCents !== 0 || summary.cash.expenseCents !== 0;

  return <div className="page-stack overview-page">
    <div className="page-heading"><div><div className="eyebrow">SEU NEGÓCIO, EM PERSPECTIVA</div><h1>Visão geral</h1><p>O que importa para organizar seu dia e planejar os próximos passos.</p></div><a className="button button-primary" href="#calendar"><CalendarDays size={17} />Ver agenda<ArrowUpRight size={15} /></a></div>
    <div className="stats-grid">
      <a href="#finance" className="stat-card"><div className="stat-top"><span>Saldo de caixa</span><span className="stat-icon teal"><Wallet size={20} /></span></div><strong className={`stat-value ${summary.cash.balanceCents < 0 ? 'text-danger' : ''}`}>{money(summary.cash.balanceCents)}</strong><span className="stat-note">Saldo realizado ao final do mês</span></a>
      <a href="#calendar" className="stat-card"><div className="stat-top"><span>Visitas agendadas</span><span className="stat-icon blue"><CalendarDays size={20} /></span></div><strong className="stat-value">{summary.scheduledVisits}<small> no mês</small></strong><span className="stat-note">Compromissos com status agendada</span></a>
      <a href="#quotes" className="stat-card"><div className="stat-top"><span>Orçamentos em aberto</span><span className="stat-icon amber"><FileText size={20} /></span></div><strong className="stat-value">{money(summary.openQuoteCents)}</strong><span className="stat-note">Rascunhos e enviados · todos os períodos</span></a>
      <a href="#inventory" className="stat-card"><div className="stat-top"><span>Atenção ao estoque</span><span className="stat-icon violet"><Package size={20} /></span></div><strong className="stat-value">{summary.lowStockCount}<small> {summary.lowStockCount === 1 ? 'material' : 'materiais'}</small></strong><span className="stat-note">No mínimo ou abaixo do limite cadastrado</span></a>
    </div>
    <div className="overview-middle">
      <section className="card cash-chart-card"><div className="card-header"><div><h2>Fluxo de caixa</h2><p>Entradas e saídas realizadas em {monthLabel}</p></div><a href="#finance" className="text-link">Detalhes<ArrowUpRight size={15} /></a></div><div className="cash-chart-summary"><div><span><span className="legend-dot income" />Entradas</span><strong>{money(summary.cash.incomeCents)}</strong></div><div><span><span className="legend-dot expense" />Saídas</span><strong>{money(summary.cash.expenseCents)}</strong></div><div className="cash-opening"><span>Saldo inicial</span><strong>{money(summary.cash.openingCents)}</strong></div></div>
        {hasCash ? <><div className="overview-chart" role="img" aria-label={`Fluxo realizado: entradas ${money(summary.cash.incomeCents)}, saídas ${money(summary.cash.expenseCents)}. Os valores diários estão disponíveis na tabela abaixo.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={summary.cash.series} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><defs><linearGradient id="cash-income" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#119c91" stopOpacity={0.2} /><stop offset="100%" stopColor="#119c91" stopOpacity={0.01} /></linearGradient><linearGradient id="cash-expense" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#de9770" stopOpacity={0.12} /><stop offset="100%" stopColor="#de9770" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f3" strokeDasharray="4 4" /><XAxis dataKey="date" tickFormatter={(value: string) => value.slice(-2)} tickLine={false} axisLine={false} minTickGap={24} tick={{ fill: '#7f8b9b', fontSize: 11 }} /><YAxis tickFormatter={(value: number) => compactMoney.format(value / 100)} tickLine={false} axisLine={false} width={72} tick={{ fill: '#7f8b9b', fontSize: 11 }} /><Tooltip labelFormatter={(label) => dateLabel(String(label))} formatter={(value, name) => [money(Number(value)), name === 'incomeCents' ? 'Entradas' : 'Saídas']} contentStyle={{ borderRadius: 12, border: '1px solid #e3e8ed', fontSize: 12 }} /><Area type="linear" dataKey="expenseCents" stroke="#de9770" strokeWidth={2} fill="url(#cash-expense)" isAnimationActive={false} /><Area type="linear" dataKey="incomeCents" stroke="#119c91" strokeWidth={2.5} fill="url(#cash-income)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div><details className="chart-data"><summary>Ver valores por dia</summary><div className="table-wrap"><table className="data-table"><thead><tr><th>Data</th><th>Entradas</th><th>Saídas</th><th>Saldo</th></tr></thead><tbody>{summary.cash.series.map((day) => <tr key={day.date}><td>{dateLabel(day.date)}</td><td>{money(day.incomeCents)}</td><td>{money(day.expenseCents)}</td><td>{money(day.balanceCents)}</td></tr>)}</tbody></table></div></details></> : <EmptyState title="Um novo mês para organizar" description="Os lançamentos realizados aparecerão aqui. Cadastre suas entradas e saídas para acompanhar o caixa." action={<a className="button button-secondary" href="#finance">Adicionar lançamento<ArrowRight size={15} /></a>} />}
      </section>
      <section className="card pipeline-card"><div className="card-header"><div><h2>Serviços por etapa</h2><p>Todos os serviços cadastrados</p></div><span className="count-pill">{totalServices}</span></div><div className="pipeline-list">{serviceStages.map((stage) => { const count = stageCounts.get(stage) ?? 0; return <a key={stage} className={`pipeline-row stage-${stage}`} href="#services"><div><span className="stage-dot" /><span>{serviceStageLabels[stage]}</span><strong>{count}</strong></div><div className="pipeline-track"><span style={{ width: totalServices ? `${count / totalServices * 100}%` : '0%' }} /></div></a>; })}</div><a className="card-footer-link" href="#services">Abrir quadro de serviços<ArrowRight size={16} /></a></section>
    </div>
    <div className="overview-bottom">
      <section className="card upcoming-card"><div className="card-header"><div><h2>Próximas visitas</h2><p>Compromissos ainda por realizar em {monthLabel}</p></div><a href="#calendar" className="text-link">Ver agenda<ArrowUpRight size={15} /></a></div>{upcoming.length ? <div className="upcoming-list">{upcoming.map((visit) => { const local = localDateTime(visit.startAt, data.timeZone); return <a className="upcoming-item" key={visit.id} href="#calendar"><div className="visit-date-tile"><strong>{local.slice(8, 10)}</strong><span>{new Intl.DateTimeFormat('pt-BR', { month: 'short', timeZone: data.timeZone }).format(new Date(visit.startAt)).replace('.', '')}</span></div><div className="upcoming-info"><strong>{visit.title}</strong><span>{clientNames.get(visit.clientId ?? '') || 'Sem cliente vinculado'}</span>{visit.location && <small><MapPin size={12} />{visit.location}</small>}</div><span className="upcoming-time" title={dateTime(visit.startAt, data.timeZone)}><Clock3 size={13} />{local.slice(11)}</span><ArrowUpRight size={15} className="muted" /></a>; })}</div> : <EmptyState title="Nenhuma visita futura neste mês" description="Sua agenda fica pronta para o próximo atendimento assim que você cadastrar uma visita." action={<a className="text-link" href="#calendar">Organizar agenda<ArrowRight size={15} /></a>} />}</section>
      <section className="card stock-alert-card"><div className="card-header"><div><h2>Reposição de materiais</h2><p>Saldo comparado ao mínimo de cada material</p></div><span className={`badge ${lowStock.length ? 'badge-warning' : 'badge-muted'}`}>{lowStock.length} {lowStock.length === 1 ? 'alerta' : 'alertas'}</span></div>{lowStock.length ? <><div className="stock-alert-list">{lowStock.slice(0, 4).map((material) => <a href="#inventory" className="stock-alert-item" key={material.id}><span className="small-icon amber"><Package size={17} /></span><div><strong>{material.name}</strong><span>Mínimo: {quantity(material.minimumMilli)} {material.unit}</span></div><strong className="stock-alert-quantity">{quantity(material.stockMilli)}<small>{material.unit}</small></strong></a>)}</div><a href="#inventory" className="card-footer-link">Ver estoque completo<ArrowRight size={16} /></a></> : <EmptyState title={data.materials.length ? 'Nenhum material abaixo do limite' : 'Estoque sem materiais cadastrados'} description={data.materials.length ? 'Os materiais ativos estão acima dos seus limites mínimos.' : 'Cadastre os materiais e seus limites para acompanhar a reposição.'} action={<a className="text-link" href="#materials">Ver catálogo<ArrowRight size={15} /></a>} />}</section>
    </div>
    <div className="overview-outstanding"><span><ArrowDownLeft size={17} /><span>A receber · todos os períodos</span><strong>{money(summary.cash.receivableCents)}</strong></span><span><ArrowUpRight size={17} /><span>A pagar · todos os períodos</span><strong>{money(summary.cash.payableCents)}</strong></span><a className="text-link" href="#finance">Gerenciar lançamentos<ArrowRight size={15} /></a></div>
  </div>;
}
